
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wineproject?serverTimezone=Hongkong
    username: root
    password: 123



mybatis:
  mapper-locations: mapper/*.xml